version: '3.8'

services:
  db:
    image: postgres:15
    container_name: autoflex-db
    environment:
      POSTGRES_DB: autoflex_db
      POSTGRES_USER: autoflex
      POSTGRES_PASSWORD: autoflex
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
